### ISSUE TITLE
Varying-coefficient spline models result in duplicated names

### ISSUE THREAD

**Issue by jburos** [generable/hierarchy#2]
Reminder to do this when we get to a place to clean up codebase - See for example https://github.com/generable/ramsey-models/pull/8/commits/2420cdbb15e96cfd00b58bb413a63fb5e4b276e2

**Comment by krzysztofsakrejda** [comment]
Fixed in this PR: https://github.com/generable/hierarchy/pull/9/files

Splines now generate column names, that pattern will expand to any other similar function terms.
