### ISSUE TITLE
k=3 should never be used

### ISSUE THREAD

**Issue by jburos** [generable/hierarchy#3]
See, for example, this model: https://github.com/generable/ramsey-models/pull/8/commits/6edaa2b97a702ef001955c7fb2ce2343fdfd21d0 

And this related issue: https://github.com/generable/ramseyutils/issues/10

**Comment by krzysztofsakrejda** [comment]
This is disallowed in the WIP testing/bugfix PR: https://github.com/generable/hierarchy/pull/9/files
